channels:
- conda-forge
- pytorch
dependencies:
- python=3.8.2
- pytorch>=1.6.0
- torchvision
- pip
- pip:
  - git+https://github.com/anupash147/mlflow.git@stable
  - boto3
  - pytorch-lightning
  - ax-platform

