channels:
- conda-forge
dependencies:
- python=3.8.2
- pip
- pip:
  - git+https://github.com/anupash147/mlflow.git@stable
  - boto3
  - pytorch-lightning
  - ax-platform
  - torch>=1.6.0
  - torchvision
