channels:
- conda-forge
dependencies:
- python=3.8.2
- pip
- pip:
  - sklearn
  - cloudpickle==1.6.0
  - git+https://github.com/anupash147/mlflow.git@stable
  - boto3
  - torch==1.6.0
  - torchvision==0.7.0
