name: tutorial
channels:
  - conda-forge
dependencies:
  - python=3.6
  - python.app
  - pip
  - pip:
    - git+https://github.com/anupash147/mlflow.git@stable
    - boto3
    - cloudpickle=0.6.1
    - numpy==1.14.3
    - matplotlib==3.0.2
    - pandas==0.22.0
    - scikit-learn==0.19.1
