channels:
- pytorch
- conda-forge
dependencies:
- python=3.8.2
- pytorch
- pip
- pip:
  - git+https://github.com/anupash147/mlflow.git@stable
  - pandas
  - scipy
  - captum
  - boto3
  - sklearn
  - prettytable
  - ipython

