name: multistep
channels:
  - conda-forge
dependencies:
  - python=3.6
  - pyspark
  - requests
  - click
  - pip
  - pip:
    - tensorflow==1.15.2
    - keras==2.2.4
    - git+https://github.com/anupash147/mlflow.git@stable
    - boto3
