name: lightgbm-example
channels:
  - conda-forge
dependencies:
  - python=3.6
  - pip
  - pip:
      - git+https://github.com/anupash147/mlflow.git@stable
      - boto3
      - matplotlib
      - lightgbm
