channels:
- conda-forge
- pytorch
dependencies:
- python=3.8.2
- pytorch=1.8.0
- pytorch-lightning==1.0.2
- pip
- pip:
  - git+https://github.com/anupash147/mlflow.git@stable
  - boto3
  - torchvision==0.9.1
