name: pytorch_example
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.6
  - pip
  - pip:
    - torch==1.8.1
    - torchvision==0.9.1
    - git+https://github.com/anupash147/mlflow.git@stable
    - boto3
    - tensorboardX
