channels:
- conda-forge
dependencies:
- python=3.8.2
- pip
- pip:
  - git+https://github.com/anupash147/mlflow.git@stable
  - boto3
  - torch==1.8.0
  - torchvision==0.9.1
  - pytorch-lightning==1.0.2
